name: CI Linting

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.6, 3.7, 3.x]

    env:
      things_to_lint: 'mquest examples/examples.py'

    steps:
    - uses: actions/checkout@v1

    - name: Hello, world test
      run: echo Hello, world!

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'

    - name: Log Python version
      run: |
        python -V
        python -c "import sys; print(sys.version)"

    - name: Log things to lint
      run: echo things_to_lint=$things_to_lint
      shell: bash

    - name: Install linters
      run: |
        python -m pip install --upgrade pip
        pip install flake8 mypy pylint

    - name: Log installed package versions
      run: pip freeze

    - name: Run Flake8
      run: flake8 $things_to_lint
      shell: bash

    - name: Run Pylint
      run: pylint $things_to_lint
      shell: bash

    - name: Run isort
      run: isort -rc $things_to_lint --check-only --diff
      shell: bash

    - name: Run mypy
      run: mypy $things_to_lint
      shell: bash
